version = 0.1

[default.deploy.parameters]
confirm_changeset = true
resolve_s3 = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
s3_prefix = "optimizeMeal"
image_repositories = []

[default.global.parameters]
stack_name = "optimizeMeal"
region = "us-east-1"
